shorter_names = {
    "Hilton Fort Lauderdale Marina": "Hilton",
    "FLL Ft. Lauderdale/Hollywood International": "FLL",
    "Wyndham Garden Ft Lauderdale Airport & Cruise Port": "Wyndham Garden FLL",
    "Sheraton Suites Plantation": "Sheraton FLL",
    "Hyatt Place Fort Lauderdale Cruise Port": "Hyatt Place FLL",
    "Renaissance Ft. Lauderdale": "Renaissance FLL",
    "Florida Hotel & Conference Center": "Hotel",
    "MCO Orlando International": "MCO",
    "Fairfield Inn by Marriott Orlando Airport": "Fairfield Inn MCO Airport",
    "Element Orlando International Drive": "Element MCO",
    "Sheraton Suites Orlando Airport": "Sheraton MCO",
    "Doubletree by Hilton Orlando Airport": "DoubleTree MCO Airport",
    "DoubleTree by Hilton Orlando at SeaWorld": "DoubleTree MCO at SeaWorld",
    "Embassy Suites Tampa Downtown": "Embassy TPA Downtown",
    "Embassy Suites Tampa Airport": "Embassy TPA Airport",
    "TPA Tampa International": "TPA",
    "Courtyard by Marriott Tampa Westshore/Airport": "Courtyard Westshore/Airport",
    "Courtyard by Marriott Tampa": "Courtyard by Marriott TPA",
    "RENAISSANCE TAMPA PLAZA": "Renaissance TPA Plaza",
    "Intercontinental Miami": "Inter",
    "MIA Miami International": "MIA",
    "Hampton Inn Miami- Airport West": "Hampton Inn MIA Airport W.",
    "EB HOTEL": "EB Hotel",
    "Hilton Tampa Downtown": "Hilton TPA Downtown",
    "Hilton Fort Lauderdale Beach Resort": "Hilton FLL Beach Resort",
    "HILTON FLL BEACH RESORT": "Hilton FLL Beach Resort",
    "THE WESTIN TAMPA BAY": "Westin TPA Bay",
    "The Westin Tampa Waterside": "Westin TPA Waterside",
    "Townplace Suites Orlando Airport": "Townplace Suites MCO Airport",
    "Renaissance Hotel Orlando A/P": "Renaissance MCO",
    "Hilton Garden Inn Fort Lauderdale Airport-Cruise Port": "Hilton Garden Inn FLL",
    "Bahia Mar Fort Lauderdale Beach": "Bahia Mar FLL Beach",
    "Embassy Suites by Hilton Fort Lauderdale": "Embassy FLL",
    "Hampton Inn Miami Airport West": "Hampton Inn Mia Airport W.",
    "Hyatt House Miami Airport": "Hyatt House MIA Airport",
    "Hyatt Regency Miami": "Hyatt Regency MIA",
    "Tampa Marriott Water Street": "TPA Marriott Water St.",
    "Sheraton Tampa Riverwalk": "Sheraton TPA Riverwalk",
    "Doubletree by Hilton Tampa Bay": "Doubletree Hilton TPA Bay",
    "Home2 Suites by Hilton Tampa Westshore Airport": "Home2 Suites TPA Westshore",
    "Hampton Inn Tampa - Ybor City Downtown": "Hampton Inn TPA Ybor City DT.",
    "Four Points by Sheraton Miami Airport": "4 Points Sheraton MIA",
    "SONESTA FORT LAUDERDALE BEACH": "Sonesta FLL Beach",
    "Hampton Inn & Suites by Hilton Miami-Doral/Dolphin Mall": "Hampton Inn MIA-Doral/Dolphin Mall",
    "Holiday Inn Resort Lake BV": "Holiday Inn Lake BV",
    "Element Orlando Universal Blvd": "Element MCO Universal Blvd",
    "AC Hotel by Marriott Fort Lauderdale Beach": "AC Hotel Marriott FLL Beach",
    "Hyatt Place Tampa Airport/ Westshore": "Hyatt Place TPA Airport/Westshore",
    "AC Hotel by Marriott Miami Airport West/Doral": "AC Hotel MIA Airport West/Doral",
    "AC Hotel by Marriott Fort Lauderdale Airport": "AC Hotel FLL Airport",
    "Four Points by Sheraton FLL -Dania Beach": "4 points Sheraton FLL-Dania Beach",
    "Crowne Plaza Universal (Hotel Kinetic Orlando)": "Crowne Plaza Universal",
    "JW Marriott Orlando, Grande Lakes": "JW Marriott MCO",
    "Residence Inn West Palm Beach Downtown": "Residence Inn WPB Downtown",
    "Hilton Garden Inn Sea World": "Hilton Garden Inn SeaWorld",
    "PBI Palm Beach Intl": "PBI Intl",
    "RSW Regional Southwest Airport": "RSW Airport",
    "Hotel Dello Fort Lauderdale Airport": "Hotel Dello FLL Airport",
    "Element Tampa Midtown": "Element TPA Midtown",
    "The Tampa Edition": "The TPA Edition",
}

hotels_location = {
    'NAPLES': [
        r"Naples to Hilton Naples", r"Hilton Naples to Naples"
    ],
    'FLL': [
        r"Hilton to FLL", r"FLL to Hilton",
        r"FLL to Sheraton FLL", r"Sheraton FLL to FLL",
        r"FLL to Hyatt Place FLL", r"Hyatt Place FLL to FLL",
        r"Wyndham Garden FLL to FLL", r"FLL to Wyndham Garden FLL",
        r"Bahia Mar FLL Beach to FLL", r"FLL to Bahia Mar FLL Beach",
        r"Renaissance FLL to FLL", r"FLL to Renaissance FLL",
        r"Embassy FLL to FLL",  r"FLL to Embassy",
        r"Hilton FLL Beach Resort to FLL",  r"FLL to Hilton FLL Beach Resort",
        r"Sonesta FLL Beach to FLL", r"FLL to Sonesta FLL Beach",
        r"AC Hotel Marriott FLL Beach to FLL", r"FLL to AC Hotel Marriott FLL Beach",
        r"The W Hotel to FLL", r"FLL to The W Hotel",
        r"AC Hotel FLL Airport to FLL", r"FLL to AC Hotel FLL Airport",
        r"4 points Sheraton FLL-Dania Beach to FLL", r"FLL to 4 points Sheraton FLL-Dania Beach",
        r"Hotel Dello FLL Airport to FLL", r"FLL to Hotel Dello FLL Airport"
    ],
    'MCO': [
        r"Hotel to MCO", r"MCO to Hotel",
        r"Element MCO to MCO",  r"MCO to Element MCO",
        r"Sheraton MCO to MCO", r"MCO to Sheraton MCO",
        r"DoubleTree MCO Airport to MCO", r"MCO to DoubleTree MCO Airport",
        r"DoubleTree MCO at SeaWorld to MCO", r"MCO to DoubleTree MCO at SeaWorld",
        r"MCO to Fairfield Inn MCO Airport", r"Fairfield Inn MCO Airport to MCO",
        r"Crowne Plaza Universal to MCO", r"MCO to Crowne Plaza Universal",
        r"Townplace Suites MCO Airport to MCO", r"MCO to Townplace Suites MCO Airport",
        r"Renaissance MCO to MCO", r"MCO to Renaissance MCO",
        r"Holiday Inn Lake BV to MCO", r"MCO to Holiday Inn Lake BV",
        r"JW Marriott MCO to MCO", r"MCO to JW Marriott MCO",
        r"Hilton Garden Inn SeaWorld to MCO", r"MCO to Hilton Garden Inn SeaWorld"
    ],
    'TPA': [
        r"Embassy TPA Downtown to TPA", r"TPA to Embassy TPA Downtown",
        r"Embassy TPA Airport to TPA", r"TPA to Embassy TPA Airport",
        r"Renaissance TPA Plaza to TPA", r"TPA to Renaissance TPA Plaza",
        r"TPA to Courtyard by Marriott TPA", r"Courtyard by Marriott TPA to TPA",
        r"Courtyard Westshore/Airport to TPA", r"TPA to Courtyard Westshore/Airport",
        r"AC Hotel Airport to TPA", r"TPA to AC Hotel Airport",
        r"Hyatt Place TPA Airport/Westshore to TPA", r"TPA to Hyatt Place TPA Airport/Westshore",
        r"Hilton TPA Downtown to TPA", r"TPA to Hilton TPA Downtown",
        r"Westin TPA Bay to TPA", r"TPA to Westin TPA Bay",
        r"Westin TPA Waterside to TPA", r"TPA to Westin TPA Waterside",
        r"TPA Marriott Water St. to TPA", r"TPA to TPA Marriott Water St.",
        r"Sheraton TPA Riverwalk to TPA", r"TPA to Sheraton TPA Riverwalk",
        r"Doubletree Hilton TPA Bay to TPA", r"TPA to Doubletree Hilton TPA Bay",
        r"Home2 Suites TPA Westshore to TPA",  r"TPA to Home2 Suites TPA Westshore",
        r"Hampton Inn TPA Ybor City DT. to TPA", r"TPA to Hampton Inn TPA Ybor City DT.",
        r"Element MCO Universal Blvd to MCO", r"MCO to Element MCO Universal Blvd",
        r"Element TPA Midtown to TPA", r"TPA to Element TPA Midtown",
        r"The TPA Edition to TPA", r"TPA to The TPA Edition"
    ],
    'MIA': [
        r"Inter to MIA", r"MIA to Inter",
        r"Hampton Inn MIA Airport W. to MIA", r"MIA to Hampton Inn MIA Airport W.",
        r"EB Hotel to MIA", r"MIA to EB Hotel",
        r"Hyatt House MIA Airport to MIA", r"MIA to Hyatt House MIA Airport",
        r"Hyatt Regency MIA to MIA", r"MIA to Hyatt Regency MIA",
        r"4 Points Sheraton MIA to MIA", r"MIA to 4 Points Sheraton MIA",
        r"Hampton Inn MIA-Doral/Dolphin Mall to MIA", r"MIA to Hampton Inn MIA-Doral/Dolphin Mall",
        r"AC Hotel MIA Airport West/Doral to MIA", r"MIA to AC Hotel MIA Airport West/Doral"
    ]
}

excel_hotels = {
    'MIA Miami International': 'MIA',
    'FLL Ft. Lauderdale/Hollywood International': 'FLL',
    'TPA Tampa International': 'TPA',
    'MCO Orlando International': 'MCO',
    'Embassy Suites Tampa Downtown': 'Embassy TPA Downtown',
    'Embassy Suites Tampa Airport': 'Embassy TPA Airport',
    'Hilton Fort Lauderdale Marina': 'Hilton FLL Marina',
    'THE WESTIN TAMPA BAY': 'Westin TPA Bay',
    'The Westin Tampa Waterside': 'Westin TPA Waterside',
    'SONESTA FORT LAUDERDALE BEACH': 'Sonesta FLL Beach',
    'NotOnFile': 'Passenger Cancelled',
    'Unknown OpenBid': 'Passenger Cancelled'
}
